* [8.2.3346](https://github.com/vim/vim/commit/2596a4e763e11eb8e406f262cb72fd2b39461572): Vim9: no error for using "." for concatenation after ":vim9cmd"\n* [Update runtime files](https://github.com/vim/vim/commit/6aa57295cfbe8f21c15f0671e45fd53cf990d404)\n* [8.2.3345](https://github.com/vim/vim/commit/bfb2bb16bc69441fa3ec13caacb2c94637a8a0ec): some code not covered by tests\n* [8.2.3344](https://github.com/vim/vim/commit/d2e9ccee90d2b39f4c9fd6cec271ef3fafd76f09): vimscript test fails\n* [8.2.3343](https://github.com/vim/vim/commit/4830c211a47f39edcf1827ffd787306faf65c2a5): Vim9: autoload test fails\n* [8.2.3342](https://github.com/vim/vim/commit/b521766c56c0e17db6e8615f35cf21012af0670c): test for :let errors fails\n* [8.2.3341](https://github.com/vim/vim/commit/88c89c77229e725ab2613b022249e2f506d82b82): Vim9: function call aborted despite try/catch
